[service_account]
type = "service_account"
project_id = "myfinetuning-project"
private_key_id = "9fbe67f304751db40bb0fbf76eaa681348b0f2fa"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqh...
-----END PRIVATE KEY-----"""
client_email = "vivek-tool-calling@myfinetuning-project.iam.gserviceaccount.com"
client_id = "102020561265516503992"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/vivek-tool-calling%40myfinetuning-project.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
