[service_account]
type = "service_account"
project_id = "myfinetuning-project"
private_key_id = "9fbe67f304751db40bb0fbf76eaa681348b0f2fa"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDn8T4D6hVWB6fn
RGvkznVLPu5AXd9S672cGlIPrOdB4D7LbC2NhMVF3C1KTOTSr/SW9TjQA0w0Zkzx
pc2BwpbDHAwrml/AYmR3L3vkNiX/aRAxNWBWjEtmgTbrZ1oucthTIQ+5LHI3Zn6Q
b0zDHc//VAnAwxw+iL2LA3xlP7KDkkYGnECF8Hqf98Jh9Dna20rM6Tjg8eDn4QRT
2n+Z43bbl5z0D5kdiRVcEUnZOnwI4aUUUcjoeMbHRU1BkmjzeXQIesy5ayi186A4
YeTvU4e2ZI40joTE035ruLqr8wx4fSTZVCYO3QgcnWAbX5rYhjBevBpeIFjsj8mu
zDbyFFO7AgMBAAECggEATDk2MbAgceTTM4gDUy7cUi2su5998HDDn8TwmfEvELGi
wVRcRglPkW1Rvvy1KF4l6eRN1uJ2jTPfbnyYJGAwDo+tmjjB5eYP8TE8LFv1MdIz
vZA2iErTzqyBQWx2MRSR7gPL+IVYRcebqVjCZ87o15alG+Gi6xQiAkjTfSypPF5a
FrAt5A93M86nNdHf36dqcZvtuIg431y1EayfzMOD6NFZhuQNzV1F5LUm1HzwEDxf
9AKHJ3/NLXQyJeHx/8ld/m7ZN7wNv9kufxhRXO1Ta6kdoSHIriKoTRi0xwPzR2Kk
2A2dxTrfLtLOSJn0khTuoyP2Zl+tY0CEb7pO2iIZsQKBgQD0dDCXD0Oh09C/N+GA
yN4MPNVY+ozvgKIFlkM2h5x8d2oJm+lU5JTiwr68MEZ8SpUWTdqoHbf9CEHB4/Z0
hke+h/gTaCF7maVnIbujU+ViAYx76Xzts8jdkhuUNIMGf0gK0mKduQPGArH1uxTt
AMu7ygqU4iDlCM/s46LIGjS1UQKBgQDy5cUIoMES+jabXjeS7U4KO7p5Z8VUZZrV
wJWAt9rXRoA9hE/WGnPxJ0qPNZ+nUcvT0uYJZMOAgYopLau9uq6kWLkqw8psGZQX
mgS3ffTBP/7xJT9p73oIbHx1aZBKfmG/5zzGS1JbNu2YayovnD5cQr4XNKrnGRD7
3gW81ealSwKBgH41btDPBLAMV/4hr7959YqD7fKeiR0uYHhZ+CGzKkvoq0qCwJkf
2u6odSlcE0ggiZCWaYnarh9pn+mm9Jt8qJXqRV5fqMnTrd3tQJ82tXtAKXPgPKvM
4qviv3JpGizEkkFkFZ4w443b3l1sVYV3n7g4u/XaOfmF7zPy4xxEy2nBAoGBAO0i
YSAxQQ2z9gftDbiFsQDQmxbXtpDUuTshz1NhK2esTprAR+kw3ix7PZFeusVxV9sv
NKHLHAqjbS0Sh26tiL6uV+hmSYML3cbE+QHjGEZqogzvXl+gCrWapE9EhjgT9n6R
1IWLF5Yxo/h/9ymQElmkV0z0gD0p/ajHczaOZaTNAoGAPC5O3ZlCFXQT/3t3EDPr
kl3JKusxrCJsVgyKtvuS6lb3rPS0zdrdGXW7hPDyu1t2DFwki+V1vWnCQv4Sw/kC
YRU7hkIqdYGPTldJjJhD1edxG5vSiP40WRbsV1hwZ70ttgnFLjGUhrXUHyy0RRVB
DqsTmT3SiJ8deg+ZTJlOWsg=
-----END PRIVATE KEY-----"""
client_email = "vivek-tool-calling@myfinetuning-project.iam.gserviceaccount.com"
client_id = "102020561265516503992"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/vivek-tool-calling%40myfinetuning-project.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
